### ISSUE TITLE
可否提供结合dva/router的例子,谢谢

### ISSUE THREAD

**Issue by cbor88** [sorrycc/dva-example-react-native#1]

**Comment by sorrycc** [comment]
印象中 RN 应该用不上 dva/router 吧。

**Comment by cbor88** [comment]
@sorrycc 好的,谢谢帮助理解, 想参考dva-init 脚手架代码的层次结构组织RN代码, 看到 package中引入了 react-dom ,以为会在RN中 整合dva/router

**Comment by sorrycc** [comment]
react-dom 其实没用，只是为了不报 peerDependencies 的 WARNING 。
